In [44]:
import pandas
import geopandas
import h3
from shapely import wkt
from shapely.geometry import Polygon
import matplotlib.pyplot as plt
import h3

In [39]:
rj_instances = pandas.read_csv("../data/cvrp-instances-1.0/train/cvrp-0-rj-0.csv")
rj_area = pandas.read_csv("/media/gegen07/Expansion/data/rj_interpolated_res_6.csv")

In [41]:
rj_area['geometry'] = rj_area.geometry.apply(wkt.loads)
rj_area = geopandas.GeoDataFrame(rj_area, geometry="geometry")

In [48]:
rj_area["h3_boundary"] = rj_area.centroid.apply(lambda x: h3.geo_to_h3(x.y, x.x, 6))

In [34]:
bag = pandas.DataFrame(rj_instances.groupby("h3_boundary").count()["id"]).reset_index()

In [35]:
bag.columns = ["h3_boundary", "count"]

In [69]:
bag

        h3_boundary  count
0   86a8a0697ffffff    381
1   86a8a06b7ffffff   1463
2   86a8a079fffffff      8
3   86a8a232fffffff      1
4   86a8a2a07ffffff      1
5   86a8a2a0fffffff     10
6   86a8a2a17ffffff      1
7   86a8a2a1fffffff      1
8   86a8a2a2fffffff     15
9   86a8a2a47ffffff    112
10  86a8a2a4fffffff      1
11  86a8a2a57ffffff    101
12  86a8a2a5fffffff      8
13  86a8a2a67ffffff    567
14  86a8a2a6fffffff     77
15  86a8a2a77ffffff    165
16  86a8a2a8fffffff      1
17  86a8a2aa7ffffff      1
18  86a8a2ac7ffffff     20
19  86a8a2ad7ffffff      1
20  86a8a2ae7ffffff    102
21  86a8a2aefffffff     10
22  86a8a2af7ffffff     10
23  86a8a2b47ffffff    115
24  86a8a2b4fffffff    207
25  86a8a2b57ffffff      4
26  86a8a2b5fffffff     63
27  86a8a2b67ffffff     37
28  86a8a2b6fffffff    245